### numpy - basic 
- 배열 랜덤생성한 후
 - 자료형 차원구하기
 - 차원별로 배열 생성하기
 - 불린인덱싱으로 공배수 조건들에 맞는 것을 출력
 - 차원 변환하기
 - 인덱싱
 - zeros-like 등 
### numpy - 응용
 - 랜덤배열에서 차원바꾸기 - (0,1,2)(3차원,2차원,1차원) 고정에서 (1,2,0) 등으로 바꾸는거 
                 


### pandas - 데이터처리
                 
### 그 외
- nan값 개수구하기
- 사용자함수 범주화하기
- 칼럼-칼럼 연결해서 새로운 칼럼을 만들고 칼럼의 이름 지정하기 join
- agg transform apply filter
- 단위기준을 변경해서 다른 칼럼으로 변환하기
- 년월일 분리하고 다시 합치고 인덱스로 셋팅하고
- 그룹화해서 다양하게 연산하기
- 데이터 전처리하기
- 시각화 - 탐색하는 문제(dataset 주어지고 시각화해서 탐색하기)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# 배열을 랜덤으로 생성하기

In [3]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 자료형 차원구하기
print(ar.ndim)

1


In [5]:
# 차원별로 배열 생성하기
# 1차원
data1 = np.array([1,2,3])
print(data1,data1.ndim)
# 2차원
data2 = np.array([[1,2,3],[4,5,6]])
print(data2,data2.ndim)
# 3차원
data3 = np.array([[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]]])
print(data3,data3.ndim)

[1 2 3] 1
[[1 2 3]
 [4 5 6]] 2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 3


In [6]:
# 불린인덱싱으로 조건에 맞는 것을 출력하기

In [7]:
# 예상문제. 1~1000까지의 숫자배열을 생성하고 3과5의 공배수들을 불린인덱싱으로 출력하세요.

In [8]:
ar = np.arange(1,1001)
ar1 = ar[ar%15==0]
print(ar1)

for i in range(1,1001):
    if i % 15 == 0:
        print(i,end="")

[ 15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255 270
 285 300 315 330 345 360 375 390 405 420 435 450 465 480 495 510 525 540
 555 570 585 600 615 630 645 660 675 690 705 720 735 750 765 780 795 810
 825 840 855 870 885 900 915 930 945 960 975 990]
153045607590105120135150165180195210225240255270285300315330345360375390405420435450465480495510525540555570585600615630645660675690705720735750765780795810825840855870885900915930945960975990

In [9]:
# 차원 변환하기
# 아래 주어진 배열에서 3차원과 2차원을 바꾸세요.
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 



In [10]:
a1 = np.transpose(a,(1,0,2))
print(a1,a1.shape)

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3)


In [11]:
# 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
[0,1,2,3,4,5,6,7,8,9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
np.sort(a)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
# zeros_like , ones_like, full_like 를 사용하세요.

In [14]:
# NAN 값의 갯수 구하기

In [ ]:
def findn(a):
    return a.isnull()
def sumnan(a):
    return a.isnull().sum()
def sumnanall(a):
    return a.isnull().sum().sum()

df2 = df.copy()
display(df2.pipe(findn).tail(5))
print(df2.pipe(sumnan),'\n')
print(df2.pipe(sumnanall))

In [17]:
df1 = pd.read_csv('C:\cakd5\workspace\m2_분석라이브러리활용\pandas\dataset/auto-mpg.csv')
print(df1.horsepower.isnull().sum())
df1.dropna(subset=['horsepower'],axis=0,inplace=True)
df1.horsepower.isnull().sum()

0


0

In [ ]:
# 사용자함수 범주화하기

In [ ]:
# age카테고리를 범주화해서 출력하세요.

In [20]:
t1=sns.load_dataset('titanic')
t1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [21]:
def get_category(age):
    cat=''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 19: cat = 'Teenager'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else:
        cat = 'Elderly'
    return cat
t1['age_cat'] = t1.age.apply(lambda x: get_category(x))
t1[['age','age_cat']].head()

age      age_cat
0  22.0  Young Adult
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult

In [ ]:
# 칼럼-칼럼 연결해서 새로운 칼럼을 만들고 칼럼의 이름 지정하기 (join함수)

In [ ]:
df1['ind'] = [1,2,3,4]
df2['ind'] = [1,2,3,4,5]
df1.set_index('ind').join(df2.set_index('ind'),lsuffix='_a',rsuffix='_b')  

In [ ]:
df1.join(df2,lsuffix='_a',rsuffix='_b',how='inner')  # 교집합
df1.join(df2,lsuffix='_a',rsuffix='_b',how='outer')  # 합집합

In [ ]:
data = np.arange(1000,5000,1000)
obj = pd.Series(data)
state = ['Califonia','Ohio','Oregon','Texas']
obj.name = 'population'
obj.index = state  
obj.index.name = 'state'  # 인덱스 이름 설정하기
obj

In [ ]:
# agg transform apply filter

In [ ]:
titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','sex','class','fare','survived']]
grouped = df.groupby(['class'])
grouped.head()

agg_all = grouped.agg(['min','max'])
agg_all.head()
agg_sep = grouped.agg({'age':'mean','fare':['min','max']})
agg_sep
grouped_filter = grouped.filter(lambda x: len(x)>=200).head()
print(grouped_filter,'\n')
grouped_filter.value_counts('class')
agg_grouped = grouped.apply(lambda x: x.describe())
agg_grouped
grouped.age.transform(z_score)[:3]

In [ ]:
# 그룹화해서 다양하게 연산하기

In [ ]:
group3 = grouped.get_group('Third')
grouped = df.groupby(['class'])
list(grouped)

In [22]:
import numpy as np
rng = pd.period_range('2000-01-01',periods=3, freq='M')
ts = pd.Series(np.random.randn(3),index=rng)
print(ts,'\n')
ts.to_timestamp(how='end')

2000-01    0.959027
2000-02   -1.233195
2000-03   -1.546111
Freq: M, dtype: float64 



2000-01-31 23:59:59.999999999    0.959027
2000-02-29 23:59:59.999999999   -1.233195
2000-03-31 23:59:59.999999999   -1.546111
dtype: float64

In [24]:
rng = pd.date_range('2001-01-01',periods=12,freq='Y')
ts = pd.Series(np.arange(12),index=rng)
ts

2001-12-31     0
2002-12-31     1
2003-12-31     2
2004-12-31     3
2005-12-31     4
2006-12-31     5
2007-12-31     6
2008-12-31     7
2009-12-31     8
2010-12-31     9
2011-12-31    10
2012-12-31    11
Freq: A-DEC, dtype: int32