In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, size=(5,5))
arr

array([[8, 5, 2, 1, 3],
       [1, 4, 2, 9, 6],
       [8, 6, 5, 4, 5],
       [5, 3, 5, 7, 6],
       [8, 1, 2, 4, 2]])

In [3]:
# 전치
arr.T

array([[8, 1, 8, 5, 8],
       [5, 4, 6, 3, 1],
       [2, 2, 5, 5, 2],
       [1, 9, 4, 7, 4],
       [3, 6, 5, 6, 2]])

In [4]:
np.transpose(arr)

array([[8, 1, 8, 5, 8],
       [5, 4, 6, 3, 1],
       [2, 2, 5, 5, 2],
       [1, 9, 4, 7, 4],
       [3, 6, 5, 6, 2]])

In [5]:
# 행렬곱, 내적
np.dot(arr.T, arr)

array([[218, 115,  99, 116, 116],
       [115,  87,  65,  90,  89],
       [ 99,  65,  62,  83,  77],
       [116,  90,  83, 163, 127],
       [116,  89,  77, 127, 110]])

In [15]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y = np.swapaxes(a, 0,1)   # 0은 2차원(열), 1은 1차원(행)
print(y,'\n')

y= a.T
y= np.transpose(a)
print(y)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]]


In [ ]:
# 1~100을 아래와 같이 출력하세요.

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [36]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [37]:
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1:
        a[i] = a[i][::-1]

print(a)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [39]:
# (0,1,2)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))
print(y,y.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3) 



In [40]:
# (1,2,3) -> (2,3,1)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0))
print(y,y.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1) 



In [5]:
#[과제] 아래배열에서 3차원과 2차원을 변경하여 출력하세요(shape확인)
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

y = np.transpose(arr,(1,0,2))
print(y,y.shape,'\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4) 



In [ ]:
#[과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요.

In [8]:
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

y = np.transpose(arr,(0,2,1))
print(y,y.shape,'\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2) 



In [2]:
import numpy as np
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')
arrs = swapaxes(1,2)
print(arr.swapaxes(1,2),arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 



NameError: name 'swapaxes' is not defined

In [46]:
# 나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [48]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value),'\n')

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1,dtype=float))

[1.17647059 0.54054054 1.         0.01      ] 

[100] 

[0.01]


In [49]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

[  4 100 225] 

[   2  100 3375]


In [52]:
arr = np.random.randn(1000000)
print(arr.mean(),'\n')
print(arr.std())

-0.001020677417742351 

1.00016753720425


In [54]:
arr = np.random.randn(10)
arr

array([-0.26175558,  0.40093554,  0.08373583,  0.98491198,  0.76025667,
       -0.49258731, -1.84812812,  0.3911196 ,  0.6202226 ,  0.82435994])

In [55]:
# 양수인 원소의 개수
(arr>0).sum()

7

In [56]:
# 하나 이상의 값이 True인지 검사
bools = np.array([False,False,True,True])
bools.any()

True

In [57]:
# 모든 원소가 True인지 검사
bools.all()

False

In [59]:
# 삼항식의 벡터화 버전
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2) # 0보다 크면 2 아니면 뒤에꺼

[[ 0.12981537 -0.3959195  -0.95540156 -0.2888514 ]
 [-0.88841045  1.01362381  1.97851525 -2.03047077]
 [-0.03564859 -0.49736515 -0.05814732 -0.74115496]
 [ 0.44486119 -0.38548915 -0.37989729  0.95231109]] 



array([[ 2, -2, -2, -2],
       [-2,  2,  2, -2],
       [-2, -2, -2, -2],
       [ 2, -2, -2,  2]])

In [60]:
# arr 의 모든 양수를 2로 바꿀 경우
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.3959195 , -0.95540156, -0.2888514 ],
       [-0.88841045,  2.        ,  2.        , -2.03047077],
       [-0.03564859, -0.49736515, -0.05814732, -0.74115496],
       [ 2.        , -0.38548915, -0.37989729,  2.        ]])

In [62]:
# 두개의 1차원 배열을 받아서 가능한 모든(x,y) 짝을 만들 수 있는 2차원 배열 2개반환
x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs,'\n')
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [65]:
# np.sort() 원본반영 안됨
np.random.seed(0)
arr = np.random.randint(1,100, size = 10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88] 

[45 48 65 68 68 10 84 22 37 88]


In [66]:
# 원본을 유지하지 않으면 sorted에 저장을 하고 출력을 해주어야한다.
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [68]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d, axis = 0) # 행방향
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d, axis = 1) # 열방향
print(sort_ar2d_axis1,'\n')

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]] 



In [75]:
# ndarray.sort(): 원본 반영
np.random.seed(0)
arr = np.random.randint(1,10,size=10)
print(arr,'\n')
arr.sort()
print(arr)

[6 1 4 4 8 4 6 3 5 8] 

[1 3 4 4 4 5 6 6 8 8]


In [79]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 열방향 정렬, default( 1or0 을 입력안했을때 1로 처리)
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(1)
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [82]:
# 행방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(0)
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[4 1 4]
 [6 2 4]
 [6 3 5]
 [8 7 7]
 [9 8 9]]


In [83]:
# 정렬된 행렬의 인덱스 반환: 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [99]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.5*len(large_arr))]

0.05332290103658159

In [100]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [4]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [5]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [6]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식, .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr)

In [8]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [11]:
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0] 을 출력하세요.
a = np.ones(10, dtype = int)
a
a[1]=0;a[3]=0;a[5]=0;a[7]=0;a[9]=0
a

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [39]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [31]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력
a= np.arange(10)
a1 = a[a>5]
a1

array([6, 7, 8, 9])

In [33]:
# Q. a에서 최대값, 최소값의 인덱스 출력
a = np.arange(1,10)
print(f'최댓값: {np.argmax(a)}\n최솟값: {np.argmin(a)}')

최댓값: 8
최솟값: 0


In [36]:
# Q. a에서 인덱스 배열을 역순으로 출력하세요
a = np.arange(1,10)
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [ ]:
# Q. np.ones((10,10))을 아래와 같이 출력하세요.

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [37]:
b=np.ones((10,10))
b[1:9,1:9]=0
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#[과제] np.ones((5,5))을 아래와 같이 출력하세요.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]


In [11]:
ar=np.ones((10,10))
ar[[0,1,8,9]]=0
ar[:,[0,1,8,9]]=0
print(ar)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [116]:
a = np.ones((5,5))
a = np.pad(a, pad_width=2, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#[과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요.(두가지방식:인덱싱,tile함수)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])


In [110]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
import numpy as np
a = np.zeros((8,8))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#[도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [13]:
a = np.arange(336).reshape(6, 7, 8)
print(np.where(a == 99))

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


In [16]:
arr = np.arange(336).reshape(6,7,8)
# print(arr)
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [ ]:
#[도전과제] np.arange(4)를 이용해서 아래와 같이 출력하세요.

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


In [115]:
a = np.diag(1+np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [17]:
zero = np.zeros((5, 5))
a = np.arange(4)

for i in range(4):
    zero[i + 1, i] = a[i] + 1
    
print(zero)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


[파이썬 random 함수]

In [56]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이의 숫자를 랜덤하게 출력
print(random.randint(1,10),'\n') # 1~10 사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20),'\n') # min(10) max(20)사이 float를 리턴
print(random.randrange(10),'\n') # 0~10 지정범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.12480808159201484 

3 

16.82467682520344 

8 

3 

[4, 3, 1] 

[1, 3, 2, 4, 5]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성(고정)
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn: 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [57]:
print(np.random.randint(6),'\n') # 0~5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1~19까지 정수인 난수 1개
print(np.random.randint(10, size=10),'\n') # 0~9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10~19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5)),'\n') # 10~19까지 정수인 난수로 3행5열 배열 생성


5 

19 

[7 1 6 7 8 2 6 9 2 9] 

[16 11 18 14 19 15 13 15 17 19] 

[[16 14 14 10 14]
 [13 16 16 14 10]
 [18 11 14 10 14]] 



In [60]:
r = np.random.rand(6) # 0 ~ 1사이의 균일분포
print(r,'\n')
r.mean()

[0.43143041 0.53161341 0.61798164 0.61709918 0.02950351 0.57110294] 



0.4664551808795441

In [97]:
# 표준 정규분포
r = np.random.randn(10000)
print(r,'\n')
r.mean()

[-1.12656493 -0.11345815  1.29016045 ... -0.46821381 -1.25828623
  0.48083494] 



0.003174667272669413

In [63]:
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

[1 2 3 4 5] 



array([2, 3, 4, 5, 1])

In [64]:
np.random.choice(list)

3

In [65]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts=True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [99]:
np.random.uniform(1.0,2.0,10)

array([1.50731302, 1.40582505, 1.7328443 , 1.25353258, 1.45146885,
       1.24235749, 1.53911978, 1.26541049, 1.98894195, 1.31437696])

In [70]:
print(np.random.uniform(0,1,(2,3)))

[[0.3729091  0.51399105 0.83520513]
 [0.721808   0.23185749 0.46865291]]


In [68]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform함수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.17390619, 0.12478354, 0.00636601],
       [0.20284729, 0.56859815, 0.80548658]])

In [71]:
!pip install pandas

In [73]:
ar = np.random.rand(4,8)
ar

array([[0.83543831, 0.49988699, 0.01972655, 0.57722549, 0.7690136 ,
        0.74259662, 0.85757704, 0.18628527],
       [0.96912481, 0.00323098, 0.71216114, 0.72659833, 0.46344827,
        0.56978756, 0.07806791, 0.51850037],
       [0.26616282, 0.07275875, 0.46539223, 0.31326641, 0.2433147 ,
        0.87860691, 0.35090545, 0.29138563],
       [0.3132006 , 0.80887465, 0.29867142, 0.02421544, 0.65196394,
        0.96536559, 0.40311895, 0.12133035]])

In [77]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
print(df,type(df))

          0         1         2         3         4         5         6  \
0  0.835438  0.499887  0.019727  0.577225  0.769014  0.742597  0.857577   
1  0.969125  0.003231  0.712161  0.726598  0.463448  0.569788  0.078068   
2  0.266163  0.072759  0.465392  0.313266  0.243315  0.878607  0.350905   
3  0.313201  0.808875  0.298671  0.024215  0.651964  0.965366  0.403119   

          7  
0  0.186285  
1  0.518500  
2  0.291386  
3  0.121330   <class 'pandas.core.frame.DataFrame'>


In [81]:
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.835438  0.499887  0.019727  0.577225  0.769014  0.742597  0.857577   
1  0.969125  0.003231  0.712161  0.726598  0.463448  0.569788  0.078068   
2  0.266163  0.072759  0.465392  0.313266  0.243315  0.878607  0.350905   
3  0.313201  0.808875  0.298671  0.024215  0.651964  0.965366  0.403119   

       time  
0  0.186285  
1  0.518500  
2  0.291386  
3  0.121330

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요.

In [83]:
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df


ID Gender Age
1  7786      M  32
2  5924      F  14
3  5525      M  28

In [117]:
ar = np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
#df.id = np.array([1,2,3,4])
df.id = np.arange(1,5)
#df.gender = np.array([0,1,0,1])
np.random.seed(0)
df.gender = np.random.randint(2, size=4)
#df.age = np.array([20,30,40,50])
df.age = np.arange(1,5) * 10
df

id  gender  age
0   1       0   10
1   2       1   20
2   3       1   30
3   4       0   40

[과제] 아래 가이드를 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요.(관측치 1000개)

- id : 1~1000번 일련번호
- gender : 0,1정수 난수 생성
- age : 0~80사이 정수 난수 생성
- region : 1 ~ 10사이 정수 난수 생성 
- product : 제품코드 11111 - 99999
- price_19 : 1000~50000 사이 실수 난수 생성
- price_20 : 1000~50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01~24사이 정수 난수 생성
- time_20 : 01~24사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [32]:
ar=np.zeros((1000,15))
columns = ['id','gender','age','region','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(ar,index,columns=columns)
df.id = np.arange(1,1001)
df.gender = np.random.randint(2,size=1000)
df.age = np.random.randint(0,81,size=1000)
df.region = np.random.randint(1,11,size=1000)
df.product_19 = np.random.randint(1111,100000,size=1000)
df.product_20 = np.random.randint(1111,100000,size=1000)
df.price_19 = np.random.uniform(1000,50001,size=1000)
df.price_20 = np.random.uniform(1000,50001,size=1000)
df.quantity_19 = np.random.randint(1,101,size=1000)
df.quantity_20 = np.random.randint(1,101,size=1000)
df.time_19 = np.random.randint(1,25, size=1000)
df.time_20 = np.random.randint(1,25, size=1000)
df.amount_19 = (df.price_19*df.quantity_19)
df.amount_20 = (df.price_20*df.quantity_20)
df.sales = np.where(df.amount_20>df.amount_19,1,0)
df

id  gender  age  region  product_19  product_20      price_19  \
0       1       1   73      10       97283       17892  47844.619486   
1       2       0   25      10       50740       36932  47559.037971   
2       3       0   46       4       18236       15399   5431.643217   
3       4       1   76       2       43717       65118  46606.625048   
4       5       0    1       7       81186       32301  33025.001839   
..    ...     ...  ...     ...         ...         ...           ...   
995   996       0   57       4       62076       45744  33772.222516   
996   997       1   59       6       72602       83082   4137.188093   
997   998       1   22       4       90260       52053  17861.498069   
998   999       1    7      10       97347        9090  43211.966369   
999  1000       0   56      10       60038       66595  30188.220096   

         price_20  quantity_19  quantity_20  time_19  time_20     amount_19  \
0    13800.699158           36           99       10        5  1.722406e+06   
1    22077.262976           92           67       16        2  4.375431e+06   
2    21388.371463           31           10        6       10  1.683809e+05   
3     4251.956933           82           57        4       10  3.821743e+06   
4    16585.087012           39           55        5        9  1.287975e+06   
..            ...          ...          ...      ...      ...           ...   
995  38274.946486           54           93       15        9  1.823700e+06   
996  21403.198285           30           46        3        3  1.241156e+05   
997  12722.615101           20           59        3        3  3.572300e+05   
998   7980.364337           34           51       16       11  1.469207e+06   
999  36018.678514           47           64        7        1  1.418846e+06   

        amount_20  sales  
0    1.366269e+06      0  
1    1.479177e+06      0  
2    2.138837e+05      1  
3    2.423615e+05      0  
4    9.121798e+05      0  
..            ...    ...  
995  3.559570e+06      1  
996  9.845471e+05      1  
997  7.506343e+05      1  
998  4.069986e+05      0  
999  2.305195e+06      1  

[1000 rows x 15 columns]

In [20]:
import string
import warnings
warnings.filterwarnings('ignore')

arr = np.zeros((1000,15))
columns = ['id','gender','age','region','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(arr,index,columns = columns)

id_arr = np.arange(1,1001) ; np.random.shuffle(id_arr) ; df.id = id_arr
gender_ar = np.array(['남','여']) ; df.gender = np.array(np.random.choice(gender_ar) for _ in range(1000))
df.age = np.random.randint(80,size = 1000)
df.region = np.random.randint(10,size = 1000)
def code(a):
    li = []
    for _ in range(a):
        result = ""
        for _ in range(2):
            result += random.choice(string.ascii_uppercase)
        for _ in range(3):
            result += random.choice(string.digits)
        li.append(result)
    return np.array(li)
df.product_19 = code(1000)
df.product_20 = code(1000)
df.price_19 = np.random.rand(1000)*499000+1000
df.price_20 = np.random.rand(1000)*499000+1000
df.quantity_19 = np.random.randint(1,101,size=1000)
df.quantity_20 = np.random.randint(1,101,size=1000)
time_ar = []
for _ in range(1,25):                   # df.time_19 = np.random.randint(1,25,size=1000).astype(str)       # 이 방식 안돼..
    time_ar.append(f'{_}'.zfill(2))     # df.time_19 = df.time_19.str.zfill(2)
np.array(time_ar)
df.time_19 = np.array(np.random.choice(time_ar) for _ in range(1000))
df.time_20 = np.array(np.random.choice(time_ar) for _ in range(1000))
# df.time_19 = np.random.randint(1,25,size=1000)
# df.time_20 = np.random.randint(1,25,size=1000)
df.amount_19 = df.price_19 * df.quantity_19
df.amount_20 = df.price_20 * df.quantity_20
for _ in range(1000):
    if df.amount_19[_] <= df.amount_20[_]:
        df.sales[_] = 1
    else:
        df.sales[_] = 0
#pd.Series(df.sales).astype(int)
pd.options.display.float_format = '{:.2f}'.format
df

id gender  age  region product_19 product_20  price_19  price_20  \
0    752      여   73       3      WL791      UJ673 358664.76 296794.36   
1    792      남   66       6      VY658      NG697 184589.70 298987.79   
2     95      여    3       3      SM832      YI430 475285.53 470930.05   
3    611      남   12       7      MD500      II882 464317.40 367861.73   
4    514      여   40       1      QK572      IU803 241857.46  78096.12   
..   ...    ...  ...     ...        ...        ...       ...       ...   
995   16      남   60       3      MP499      OF690  16137.72 275142.80   
996  971      남   63       7      JR656      UQ028 330007.07  22952.79   
997  540      여   48       5      RG011      YR431 486852.98 484727.15   
998  165      여   52       6      VG245      GL131 300435.48 369698.38   
999  403      여   55       0      TF690      LN431 150499.02 429602.91   

     quantity_19  quantity_20 time_19 time_20   amount_19   amount_20  sales  
0             77           48      24      21 27617186.42 14246129.11   0.00  
1             42           52      17      09  7752767.34 15547364.94   1.00  
2             58            8      02      21 27566561.01  3767440.37   0.00  
3              6           89      24      16  2785904.43 32739694.04   1.00  
4             29           36      21      13  7013866.27  2811460.15   0.00  
..           ...          ...     ...     ...         ...         ...    ...  
995           74           78      23      03  1194191.52 21461138.65   1.00  
996           40           44      19      22 13200282.61  1009922.80   0.00  
997           31           74      01      17 15092442.52 35869809.02   1.00  
998           90           34      18      01 27039193.64 12569744.91   0.00  
999           12           26      16      15  1805988.28 11169675.55   1.00  

[1000 rows x 15 columns]

In [27]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(111,222,size = customer)
df.product_20 = np.random.randint(111,222,size = customer)

pricearray= np.random.randint(10,500,size = 1000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df

id gender  age  product_19  product_20  price_19  price_20  \
1        1      M   40         220         150     30900     31800   
2        2      F   29         171         123     38300     24600   
3        3      F   25         158         195     26600     40800   
4        4      M   19         126         186     46600      7400   
5        5      F   68         147         187      3400     10100   
...    ...    ...  ...         ...         ...       ...       ...   
996    996      M   24         159         192      2500      8100   
997    997      M   53         218         203     48200     34300   
998    998      M   24         114         189      5900     18600   
999    999      F   73         175         167      4000     11500   
1000  1000      M   42         148         117      7800     37900   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              81           71       14        5    2502900    2257800      0  
2              18           83       19        1     689400    2041800      1  
3              41           34       19        5    1090600    1387200      1  
4              61           52       16       19    2842600     384800      0  
5              82           53       15       19     278800     535300      1  
...           ...          ...      ...      ...        ...        ...    ...  
996            18           44       20       13      45000     356400      1  
997            97           96       15       16    4675400    3292800      0  
998            97           22       14       10     572300     409200      0  
999            12           14        1       11      48000     161000      1  
1000           43           72       21       16     335400    2728800      1  

[1000 rows x 14 columns]

In [29]:
df[df.sales==0]

id gender  age  product_19  product_20  price_19  price_20  quantity_19  \
1      1      M   40         220         150     30900     31800           81   
4      4      M   19         126         186     46600      7400           61   
8      8      F   55         212         168     32800     18500           77   
9      9      F    1         153         132     47900     43600           71   
11    11      F   68         194         123     48900     24600           34   
..   ...    ...  ...         ...         ...       ...       ...          ...   
992  992      M   22         138         157      9200     21600           45   
993  993      M   62         167         116     11500     14800           49   
995  995      M   42         142         119     18700      4400           60   
997  997      M   53         218         203     48200     34300           97   
998  998      M   24         114         189      5900     18600           97   

     quantity_20  time_19  time_20  amount_19  amount_20  sales  
1             71       14        5    2502900    2257800      0  
4             52       16       19    2842600     384800      0  
8             55       20       23    2525600    1017500      0  
9             11       19        3    3400900     479600      0  
11            42        8        2    1662600    1033200      0  
..           ...      ...      ...        ...        ...    ...  
992           11       10       16     414000     237600      0  
993            7       24        4     563500     103600      0  
995           32       23       13    1122000     140800      0  
997           96       15       16    4675400    3292800      0  
998           22       14       10     572300     409200      0  

[512 rows x 14 columns]