Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [244]:
!pip install numpy

In [245]:
import numpy as np
z = np.arange(10)
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [246]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [247]:
%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 13 ms


In [248]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 598 ms


In [12]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분포에서 난수 매트릭스 array 생성
data = np.random.randn(2,3) # 표준 정규분포로 구성되는 2행 3열 매트릭스(행렬)
print(data,'\n')
print(data * 10,'\n')
print(data + data)

[[-0.732177   -0.0226625   1.40573699]
 [-0.24890618  0.14677068 -0.465407  ]] 

[[-7.32177005 -0.22662504 14.05736987]
 [-2.48906183  1.46770678 -4.65406998]] 

[[-1.46435401 -0.04532501  2.81147397]
 [-0.49781237  0.29354136 -0.930814  ]]


In [13]:
print(data.shape) # 크기
print(data.dtype) # 데이터 타입
print(data.ndim) # 차원

(2, 3)
float64
2


다차원 배열
<img src = 'numpy차원.jpg' STYLE='width:300px;'>

In [18]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [20]:
print(arr2.ndim,'\n')
print(arr2.shape)

2 

(2, 4)


In [23]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape) # (,열)이 아닌 (열,) 형태로 출력

[1 2 3] <class 'numpy.ndarray'> (3,)


In [27]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터
array2 = np.array([[1,2,3],[2,3,4]])
print(array2,type(array2),array2.shape)


[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)


In [29]:
# 1개의 row와 3개의 column 으로 구성된 2차원 배열 # 2차원으로 나타낼때 대괄호 1번 더
array21 = np.array([[1,2,3]])
print(array21,array21.shape)

[[1 2 3]] (1, 3)


In [37]:
# 3차원 (2차원을 여러개 포함시켜서 3차원을 만듬)
array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                   [[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]]])
print(array3,array3.shape,'\n')
print(type(array3))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] (3, 2, 5) 

<class 'numpy.ndarray'>


In [39]:
# 경고 메시지 제외 처리
import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특징 값으로 초기화하는 zeros,ones,full,eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [40]:
print(np.zeros(10),'\n') # 1차원
print(np.zeros((3,6)),'\n') # 2차원
print(np.zeros((2,3,2))) # 3차원 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [43]:
print(np.ones((2,3,2))) 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [44]:
ar1 = np.full((2,2),5) # 2행 2열짜리를 5로 처리
print(ar1)

[[5 5]
 [5 5]]


In [47]:
# 항등행렬, 단위행렬
ar2 = np.eye(3)
ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.(구글링)

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()

ar1 = np.zeros_like(a)
ar2 = ar1.astype(float)
print(ar2, ar2.dtype)
print()

ar3 = np.ones_like(a)
ar4 = ar3.astype(float)
print(ar4, ar4.dtype)
print()

ar5 = np.full_like(a, 6)
ar6 = ar5.astype('float32')
print(ar6, ar6.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]] float32


In [239]:
# zeros_like 예제
a = np.arange(6)
a = a.reshape((2,3))
np.zeros_like(a)



array([[0, 0, 0],
       [0, 0, 0]])

In [240]:
# ones_like 예제
a = np.arange(6)
a = a.reshape((2,3))
np.ones_like(a)


array([[1, 1, 1],
       [1, 1, 1]])

In [241]:
# full_like 예제
a = np.arange(6,dtype = int)
np.full_like(a,1)

array([1, 1, 1, 1, 1, 1])

In [48]:
# arange 함수 : python range함수의 배열버전
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
# 일반 range함수는 for문을 사용해서 처리해야함(속도차이)
arr2 = range(15)
arr2

range(0, 15)

In [52]:
arr2 = arr1.reshape(3,5) # reshape안에 들어갈 행과 열을 잘 맞춰줘야함
print(arr2,arr2.shape,'\n')
arr3 = arr1.reshape(1,3,5)
print(arr3,arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


In [53]:
# Q. array1을 생성하고 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요.
array1 = np.arange(10)
array2 = array1.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
#0~29 일차원 배열을 생성한 후 다시 2,3차원 배여로 변환하여 출력하세요.
array1 = np.arange(30)
array2 = array1.reshape(5,6)
print(array2,array2.shape,'\n')
array3 = array2.reshape(2,3,5)
print(array3,array3.shape)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] (2, 3, 5)


In [60]:
# reshape(-1,-1)이용, 차원변경 
array1 = np.arange(30)
ar12 = array1.reshape(3,-1) # 행은 3이고 나머지는 알아서 정렬
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5) # 2행 5열짜리 등록, 나머지는 알아서 계산
print(ar13,ar13.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [65]:
# 2 -> 1,3 차원으로 변환
ar1=ar12.reshape(-1,)
ar3=ar12.reshape(-1,2,5)
print(ar1,ar1.shape,'\n')
print(ar3,ar3.shape,'\n')


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [68]:
# 3 -> 1,2차원으로 변환
ar3
ar4 = ar3.reshape(-1,)
ar5 = ar3.reshape(2,-1)
print(ar4,ar4.shape,'\n')
print(ar5,ar5.shape,'\n')


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] (2, 15) 



행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [70]:
# 정방행렬
a = np.full((5,5),7)
a


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [71]:
# 항등행렬,단위행렬
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
# 영행렬
a = np.zeros(25)
a.reshape(5,-1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ndarray 데이터 형태 지정 및 변경
<img src='데이터형태.jpg' STYLE='width=300'>

In [76]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2,arr2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32


In [79]:
# 타입 변경 (astype)
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [81]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
# empty 함수: shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다. cf.zeros함수
# empty함수를 실행할 때마다 값이 다른 것을 확인할 수 있다. 이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.
print(np.empty(shape=(10,), dtype=np.int8))
print(np.zeros(shape=(10,), dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]


In [89]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4], dtype = 'S')
arr = np.array([1,2,3,4], dtype = np.string_)
print(arr,arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [88]:
arr1 = arr.astype(float)
print(arr1,arr1.dtype)

[1. 2. 3. 4.] float64


In [90]:
arr1 = arr.astype('float32')
print(arr1,arr1.dtype)

[1. 2. 3. 4.] float32


In [95]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3]
array_e1 = np.array(list_e)
print(array_e1,array_e1.dtype,'\n')
array_e2 = array_e1.astype(int)
print(array_e2,array_e2.dtype)

[1.2 2.3 3. ] float64 

[1 2 3] int32


In [98]:
# 배열의 산술 연산
#arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [99]:
arr * arr 

array([[ 1,  4,  9],
       [16, 25, 36]])

In [100]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [101]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [102]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [112]:
# 기본 사칙연산
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)

print(value2+value1)
print(np.add(value1,value2),'\n')

print(value2-value1)
print(np.subtract(value2,value1),'\n')

print(value2*value1)
print(np.multiply(value2,value1),'\n')

print(value2/value1)
print(np.divide(value2,value1))

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [119]:
arr = np.random.randn(2,2)
arr

array([[ 0.91196792, -0.27297935],
       [-0.17289352, -0.78549745]])

In [120]:
arr.mean().round(4) # 평균구하기 mean

-0.0799

In [121]:
arr.mean(axis=1) # 행 방향 

array([ 0.31949428, -0.47919548])

In [122]:
arr.mean(axis=0) # 열 방향

array([ 0.3695372, -0.5292384])

In [123]:
arr.sum().round(4)

-0.3194

In [125]:
arr.cumprod() # 누적해서 곱함

array([ 0.91196792, -0.24894841,  0.04304157, -0.03380904])

In [126]:
# 인덱싱, 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
arr2d[2]

array([7, 8, 9])

In [128]:
arr2d[2][2]

9

In [130]:
arr2d[:,0]  # 행쪽은 다 나오고(:), 열쪽는 0번째만

array([1, 4, 7])

In [131]:
arr2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#arr2d를 다른 방식으로 아래와 같이 출력하세요.
[[1,2,3],
[4,5,6]]

In [137]:
# arr2d[:2][:]    #  슬라이싱만으로는 처리할수 없는 경우가있을때는 나눠서
arr2d[[0,2],:]


array([[1, 2, 3],
       [7, 8, 9]])

In [134]:
# arr2d에서 [3,6],[[1,2],[4,5]] 을 출력하세요.
print(arr2d[:2,2])
print()
print(arr2d[:2,:2])


[3 6]

[[1 2]
 [4 5]]


In [138]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
[14,15,16]
[3,9]
[1,7,13]

In [145]:
arr[2][2:5]

array([14, 15, 16])

In [146]:
arr[[0,1],3]

array([3, 9])

In [150]:
arr[:2,3]

array([3, 9])

In [147]:
arr[[0,1,2],[1]]

array([ 1,  7, 13])

In [149]:
arr[:3,1]

array([ 1,  7, 13])

In [156]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li,type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [159]:
# Boolean indexing (참,거짓)
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [162]:
# arr1d에서 일반 인덱스를 이용해서 [6,7,8,9]를 출력하세요.
arr1d = np.arange(1,10)
print(arr1d)
arr1d[5:]

[1 2 3 4 5 6 7 8 9]


array([6, 7, 8, 9])

In [ ]:
# Q. 1~14까지 ndarray를 만들어 array_e로 저장하고 (array_e/2) > 5 를 만족하는 값을 불린 인덱싱으로 출력하세요.

In [169]:
array_e = np.arange(1,15)
array_e1 = array_e[array_e/2 > 5]
print(array_e1)

[11 12 13 14]


In [183]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

[[-0.80152339 -1.76414808  0.74282617  0.45883624]
 [ 1.44692214 -0.92188313  0.57889921 -0.72330373]
 [-0.7417003  -0.89386188  0.39171008 -1.01760396]
 [ 0.04552136 -0.14831366 -0.37405035  0.52856097]
 [ 2.93813913  1.21065012 -0.62980978 -1.12826607]
 [ 0.35568757 -0.35595946 -0.30182009  0.92719494]
 [ 0.99991416  2.21843418 -1.00981045 -0.33075808]]


In [184]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [185]:
data[names == 'Bob']  # True인 것만 뽑아주기때문에 0번째와 3번째만 출력해서나옴

array([[-0.80152339, -1.76414808,  0.74282617,  0.45883624],
       [ 0.04552136, -0.14831366, -0.37405035,  0.52856097]])

In [186]:
data[names == 'Bob', 2:]

array([[ 0.74282617,  0.45883624],
       [-0.37405035,  0.52856097]])

In [187]:
# ! = 부정
data[names != 'Bob']  # 아닌것은 ! 를 사용해서 뽑아냄

array([[ 1.44692214, -0.92188313,  0.57889921, -0.72330373],
       [-0.7417003 , -0.89386188,  0.39171008, -1.01760396],
       [ 2.93813913,  1.21065012, -0.62980978, -1.12826607],
       [ 0.35568757, -0.35595946, -0.30182009,  0.92719494],
       [ 0.99991416,  2.21843418, -1.00981045, -0.33075808]])

In [191]:
# Bob이거나 Will인 것 출력
mask = (names == 'Bob')| (names == 'Will')
data[mask]

array([[-0.80152339, -1.76414808,  0.74282617,  0.45883624],
       [-0.7417003 , -0.89386188,  0.39171008, -1.01760396],
       [ 0.04552136, -0.14831366, -0.37405035,  0.52856097],
       [ 2.93813913,  1.21065012, -0.62980978, -1.12826607]])

In [194]:
# 음수를 모두 0으로 처리하여 출력
data[data<0] = 0
print(data)

[[0.         0.         0.74282617 0.45883624]
 [1.44692214 0.         0.57889921 0.        ]
 [0.         0.         0.39171008 0.        ]
 [0.04552136 0.         0.         0.52856097]
 [2.93813913 1.21065012 0.         0.        ]
 [0.35568757 0.         0.         0.92719494]
 [0.99991416 2.21843418 0.         0.        ]]


In [ ]:
#[과제] 1~100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지방식)

In [200]:
for i in range(1,101):
    if i % 3 == 0:
        print(i,end='')
        
arr = np.arange(1,100)
arr1 = [arr%3 == 0]
arr1

369121518212427303336394245485154576063666972757881848790939699

[array([False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True])]

In [9]:
arr=np.arange(1,101)
print(arr[arr%3==0])



arr_li=arr.tolist()
for i in arr_li:
    if i%3==0:
        print(i,end=" ")




[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 

In [ ]:
#[과제] 1~100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지방식)

In [243]:
for i in range(1,101):
    if i % 5 ==0 and i % 2==0:
        print(i,end='')
        
arr1d = np.arange(1,100)
arr1d1 =[(arr1d % 5 == 0) | (arr1d % 2 == 0)]
arr1d1


102030405060708090100

[array([False,  True, False,  True,  True,  True, False,  True, False,
         True, False,  True, False,  True,  True,  True, False,  True,
        False,  True, False,  True, False,  True,  True,  True, False,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False,  True, False,  True, False,  True,  True,
         True, False,  True, False,  True, False,  True, False,  True,
         True,  True, False,  True, False,  True, False,  True, False,
         True,  True,  True, False,  True, False,  True, False,  True,
        False,  True,  True,  True, False,  True, False,  True, False,
         True, False,  True,  True,  True, False,  True, False,  True,
        False,  True, False,  True,  True,  True, False,  True, False])]

In [ ]:
#[과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.

In [10]:
a = np.random.randn(10000,10000)
print(a.round(4))
print(a.mean().round(4))  # 평균
print(a.std().round(4))   # 표준편차

[[ 0.2994 -0.8761  0.8198 ...  0.1727 -0.5074 -0.8148]
 [ 0.0973 -0.374  -0.9428 ... -0.396  -0.2398 -0.3001]
 [ 0.0993  1.7962 -0.077  ...  0.3026  0.735   1.1796]
 ...
 [ 2.5979  0.973  -1.1893 ...  0.2124 -1.8218  0.0229]
 [-1.9167  0.9338  0.1821 ...  0.4559 -1.0734 -0.3125]
 [ 1.1006 -0.1652  0.1948 ...  0.0082  1.1258  0.9324]]
-0.0
1.0


In [ ]:
#[과제] 현재 사용하고 있는 numpy버전을 출력하세요.

In [216]:
import numpy
print(numpy.__version__)

1.21.2


In [ ]:
#[과제] numpy 함수의 도움말 기능을 볼수있는 방법을 수행하여 add함수의 가이드를 출력하세요.

In [236]:
#np.info('add')
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
#[과제] zeros 함수를 이용해서 아래와 같이 출력하세요
array([0.,0.,0.,0.,1.,0.,0.,0.,0.,0.])

In [222]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#[과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
[0,1,2,3,4,5,6,7,8,9]

In [232]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
np.sort(a)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [235]:
#[과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
# 인덱스를 반환하라고 했기때문에
a= np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [12]:
# 값을 반환할경우
arr = np.array([1,2,0,0,4,0])
arr_= arr[arr!=0]
print(arr_)

[1 2 4]


In [15]:
# Fancy Indexing
arr = np.empty((8,4))
arr
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [16]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [17]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [19]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')

arr[[1,5,7,2],[0,3,1,2]]     # 원하는 곳의 숫자만을 출력

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [21]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,[0,3,1,2]])  # : (행은 전부),열의 순서를 바꿈

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [24]:
# 배열 전치와 축 바꾸기
arr = np.arange(15).reshape(3,5)
print(arr,'\n')
print(arr.T)       # transpose 의 대문자 T를 주면 열과 행이 바뀐다.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
